### ISSUE TITLE
Idea: Set afk when screen lock is active

### ISSUE THREAD

**Issue by real-or-random** [flexagoon/aw-watcher-gnome#3]
There's `/org/gnome/ScreenSaver/GetActive` to check whether screen lock is active. There's even a signal `/org/gnome/ScreenSaver/ActiveChanged`.

**Comment by flexagoon** [comment]
It looks like this only triggers once on screen lock, but doesn't detect stuff like laptop lid being closed. So I guess I'll have to stick with the current exception-based method of AFK detection.

**Comment by real-or-random** [comment]
Oh, I think my suggestion was rather to use this signal as an *additional* method for setting afk, on top of what's currently used. This would increase the precision of the tracking. 

Or do you think that's not worth the complexity?

**Comment by flexagoon** [comment]
@real-or-random I haven't encountered any behavior where aw-watcher-gnome didn't detect screen being locked.

There was an issue with it counting you as AFK when no window is in focus, but that's now fixed with https://github.com/flexagoon/aw-watcher-gnome/commit/b09092f5694deb03026c9da3880ef8ebca691e1f and https://github.com/flexagoon/focused-window-dbus/commit/6d68d5435443a6a0d74ac673f137650e7ae0245a.

If you have any specific examples of aw-watcher-gnome not detecting AFK correctly, please let me know.

**Comment by real-or-random** [comment]
I see, that makes sense then! Thanks for taking care of the issues.
